<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>彩钢板-广东彩钢夹心板-夹心彩钢板-岩棉板-彩钢瓦-防火A级板房-深圳市普源新型材料有限公司</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="<?php echo $this->cssPath("bootstrap.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->cssPath("py_global.css"); ?>">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="<?php echo $this->jsPath('jquery-bootstrap.js'); ?>"></script>
    <script src="<?php echo $this->jsPath('py_global.js'); ?>"></script>
    <script src="<?php echo $this->jsPath('tools/String.js'); ?>"></script>
    <style>

    </style>
</head>
<body>
<!-- 公用的头部 -->
<div id="topblock">
    <div class="cn" style="display: none">
        <div class="nnlne"></div>
        <a href="/" class="logoc"></a>
        <div class="bblne header">
            <a href="/" class="citm selected home">首页</a>
            <a href="/about" class="citm about">关于普源</a>
            <a href="/case/list" class="citm project">工程案例</a>
            <a href="/product/list/all" class="citm product">产品展示</a>
            <a href="/application" class="citm application">产品应用</a>
            <a href="/awards" class="citm certification">荣誉资质</a>
            <a href="/news/list" class="citm news">新闻动态</a>
            <a href="/contact" class="citm contact">联系我们</a>
            <a href="javascript:void(0)" onclick="setLanguage('cn')" class="citm swce lt selected cn-select">中文</a>
            <a href="javascript:void(0)" onclick="setLanguage('en')" class="citm swce en-select">English</a>
        </div>
    </div>
    <div class="en" style="display: none">
        <div class="nnlne"></div>
        <a href="/" class="logoc"></a>
        <div class="bblne header">
            <a href="/?language=en" class="citm selected home">Home</a>
            <a href="/about?language=en" class="citm about">About us</a>
            <a href="/case/list?language=en" class="citm project">Projects</a>
            <a href="/product/list/all?language=en" class="citm product">Products</a>
            <a href="/application?language=en" class="citm application">Applications</a>
            <a href="/awards?language=en" class="citm certification">Qualification & Certification</a>
            <a href="/news/list?language=en" class="citm news">News</a>
            <a href="/contact?language=en" class="citm contact">Contact</a>
            <a href="javascript:void(0)" onclick="setLanguage('cn')" class="citm swce  lt cn-select">中文</a>
            <a href="javascript:void(0)" onclick="setLanguage('en')" class="citm swce selected en-select">English</a>
        </div>
    </div>
</div>


<!--
    作者：vincedotnet@hotmail.com
    时间：2015-06-21
    描述：以下部分放入View中，开始
-->
<!-- 广告部分 -->
<?php echo $this->layout()->content; ?>
<!--
    作者：vincedotnet@hotmail.com
    时间：2015-06-21
    描述：以上部分放入View中，结束
-->

<div id="footerblock">
    <div class="cn" style="display: none">
        <div class="container wp">
            <div class="row">
                <div class="col-xs-6">
                    <div class="xc00" style="height:50px;">
                        <div class="xc01"></div>
                        <div class="xc02 bt-company-cn"><?php echo $this->contact->name; ?></div>
                        <div class="xc03"></div>
                    </div>
                    <div class="xc04">
                        <div>
                            <div style="display:inline-block;">销售热线： <?php echo $this->contact->sale_tel; ?> &nbsp;&nbsp;传真：<?php echo $this->contact->fax; ?></div>
                        </div>
                        <div>
                            <div>公司地址： <span class="bt-companyaddress-cn"><?php echo $this->contact->company_address; ?></span></div>
                        </div>
                        <div>
                            <div>惠州工厂地址： <span class="bt-huizhoufaddress-cn"><?php echo $this->contact->factory_address_1; ?></span></div>
                        </div>
                        <div>
                            <div>广州工厂地址： <span class="bt-guangzhoufaddress-cn"><?php echo $this->contact->factory_address_2; ?></span></div>
                        </div>
                        <div>
                            <div>邮箱： <span class="bt-email-cn"><?php echo $this->contact->email; ?></span></div>
                        </div>
                    </div>


                </div>
                <div class="col-xs-6">
                    <div class="xc05">
<!--                        <div class="xc06">-->
<!--                            粤ICP备06108000号-1-->
<!--                        </div>-->
                        <div class="xc07">
                            <div>Copyright &copy; 2015 深圳市普源新型材料有限公司  版权所有</div>
                            <div>粤ICP备15109783号-1</div>
                        </div>
                        <div class="xc08">
                            <!-- JiaThis Button BEGIN -->
                            <div class="jiathis_style_32x32">
                                <a class="jiathis_button_qzone"></a>
                                <a class="jiathis_button_tsina"></a>
                                <a class="jiathis_button_tqq"></a>
                                <a class="jiathis_button_weixin"></a>
                                <a class="jiathis_button_renren"></a>
                                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                                <a class="jiathis_counter_style"></a>
                            </div>
                            <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
                            <!-- JiaThis Button END -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="en" style="display: none">
        <div class="container wp">
            <div class="row">
                <div class="col-xs-6">
                    <div class="xc00" style="height:50px;">
                        <div class="xc01"></div>
                        <div class="xc02 bt-company-en"><?php echo $this->contact->name_en; ?></div>
                        <div class="xc03"></div>
                    </div>
                    <div class="xc04">
                        <div>
                            <div style="display:inline-block;">Sale tel： <?php echo $this->contact->sale_tel; ?>&nbsp;&nbsp;Fax： <?php echo $this->contact->fax; ?></div>
                        </div>
                        <div>
                            <div>Company address： <span class="bt-companyaddress-en"><?php echo $this->contact->company_address_en; ?></span></div>
                        </div>
                        <div>
                            <div>Huizhou Factory Location： <span class="bt-huizhoufaddress-en"><?php echo $this->contact->factory_address_1_en; ?></span></div>
                        </div>
                        <div>
                            <div>Guangzhou Factory Location： <span class="bt-guangzhoufaddress-en"><?php echo $this->contact->factory_address_2_en; ?></span></div>
                        </div>
                        <div>
                            <div>Email： <span class="bt-email-en"><?php echo $this->contact->email; ?></span></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="xc05">
<!--                        <div class="xc06">-->
<!--                            粤ICP备06108000号-1-->
<!--                        </div>-->
                        <div class="xc07">
                            <div>Copyright &copy; 2015 Shenzhen Puyuan New Materials Co. Ltd</div>
                            <div>粤ICP备15109783号-1</div>
                        </div>
                        <div class="xc08">
                            <!-- JiaThis Button BEGIN -->
                            <div class="jiathis_style_32x32">
                                <a class="jiathis_button_qzone"></a>
                                <a class="jiathis_button_tsina"></a>
                                <a class="jiathis_button_tqq"></a>
                                <a class="jiathis_button_weixin"></a>
                                <a class="jiathis_button_renren"></a>
                                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                                <a class="jiathis_counter_style"></a>
                            </div>
                            <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
                            <!-- JiaThis Button END -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->jsPath('tools/language.js'); ?>"></script>
<script>
    var singleWidth;
    $('document').ready(function(){
        singleWidth = $('.gall-itm').width();
        var gi_c = 0;
        $('.gall-itm').each(function(){
            $(this).attr('index', gi_c);
            gi_c++;
        });
        gi_c = 0;
        $('#btc-lst .itm').each(function(){
            $(this).attr('index', gi_c).text(gi_c+1);
            gi_c++;
        });


        var movfunc = function(obj){
            var index = obj.attr('index');
            var x = singleWidth * index * - 1;
            $('#gall-list').animate({left: x}, 500);
            $('#btc-lst .itm').removeClass('selected');
            $('#cst-space .itm[index=' + index + ']').addClass('selected');
        };
        $('#cst-space .itm').click(function(){
            movfunc($(this));

            clearInterval($('body').data('auto-scroll-gall'));
        });
//				
        var getNI = function(obj) {
            var index = parseInt($('#btc-lst .itm.selected').attr('index'));
            var nIndex = index - 1;
            var mnd = $('#btc-lst .itm').length - 1;
            if(nIndex < 0) {
                nIndex = mnd;
            }
            if(obj.hasClass('rt')) {
                nIndex = index + 1;
                if(nIndex > mnd) {
                    nIndex = 0;
                }
            }
            return nIndex;
        };
        $('.sid-bts').click(function(){
            var nIndex = getNI($(this));
            movfunc($('#btc-lst .itm[index=' + nIndex + ']'));
            clearInterval($('body').data('auto-scroll-gall'));
        });

        var intid = setInterval(function(){
            var nIndex = getNI($('.sid-bts.rt'));
            movfunc($('#btc-lst .itm[index=' + nIndex + ']'));
        }, 5000);
        $('body').data('auto-scroll-gall', intid);


        var resizeGitm = function(){
            $('.gall-itm').width($(window).width());
            singleWidth = $('.gall-itm').width();

            var nleft = $('#btc-lst .itm.selected').attr('index') * singleWidth * -1;
            $('#gall-list').css('left', nleft);
        };

        resizeGitm();
        $(window).resize(function(){
            resizeGitm();
        });


//        $.ajax({
//            url:'/contact?type=json',
//            dataType: 'json',
//            success: function(response) {
//                console.log(response);
//                $('.bt-company-cn').text(response.name);
//                $('.bt-company-en').text(response.name_en);
//                $('.bt-companyaddress-cn').text(response.company_address);
//                $('.bt-companyaddress-en').text(response.company_address_en);
//                $('.bt-huizhoufaddress-cn').text(response.factory_address_1);
//                $('.bt-huizhoufaddress-en').text(response.factory_address_1_en);
//                $('.bt-guangzhoufaddress-cn').text(response.factory_address_2);
//                $('.bt-guangzhoufaddress-en').text(response.factory_address_2_en);
//                $('.bt-fax-cn').text(response.fax);
//                $('.bt-fax-en').text(response.fax);
//                $('.bt-saletel-cn').text(response.sale_tel);
//                $('.bt-saletel-en').text(response.sale_tel);
//                $('.bt-email-cn').text(response.email);
//                $('.bt-email-en').text(response.email);
//            }
//        });

    });
</script>
</body>
</html>